#!/bin/bash
#
# Script to make distribution archive
#

VERSION=1.0

DISTBASE=webbrewery-$VERSION

cd ..
if [ ! -d $DISTBASE ]; then {
  cp -r webbrewery $DISTBASE
}; fi

tar cf $DISTBASE.tar -X webbrewery/dist.exclude $DISTBASE
gzip $DISTBASE.tar
